#!/bin/bash 

# User automation is created on all inventory hosts.

ansible all -u root -m user -a "generate_ssh_key=yes password=devops name=automation"

# SSH key (that you generated) is copied to all inventory hosts for the automation user and stored in /home/automation/.ssh/authorized_keys.

ansible all -u root -m authorized_key -a "user=automation key={{lookup('file','/home/automation/.ssh/id_rsa.pub')}}"





